version: '3'

dotenv: ['.env']

tasks:
  run:
    desc: Run OpenHands application with Docker
    cmds:
      - |
        docker run -it \
          --pull=always \
          -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.47-nikolaik \
          -e SANDBOX_USER_ID=$(id -u) \
          -e SANDBOX_VOLUMES=$(pwd):/workspace:rw \
          -e LLM_API_KEY=$LLM_API_KEY \
          -e LLM_MODEL=$LLM_MODEL \
          -e GITHUB_TOKEN=$GITHUB_TOKEN \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ~/.openhands:/.openhands \
          --add-host host.docker.internal:host-gateway \
          --name openhands-app-$(date +%Y%m%d%H%M%S) \
          docker.all-hands.dev/all-hands-ai/openhands:0.47 \
          python -m openhands.cli.main --override-cli-mode true

  default:
    desc: Default task - run the OpenHands application
    cmds:
      - task: run
